server:
    port: 8081
spring:
    application:
        name: netty-client-demo
netty:
    client:
        config:
            ip: 127.0.0.1
            port: 8089
rocketmq:
    name-server: 172.17.0.2:9876
    producer:
        group: myGroupName